### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by raxuser100** [capesean/codegenerator#1]
Been having a look through.  Amazing work you have here. 

Is there a database to host the entities etc? 

Ray

**Comment by capesean** [comment]
Hi Ray

Thanks for the complement!

A codegenerator SQL Server database will be created by Entity Framework CodeFirst when you first run it on a local machine. It will create the tables for Projects, Entities, Fields, Relationships, etc. You just have to edit the web.config(.sample) file to set the initial database username/password, so you can login. When it first runs, it will take the values from the config file and create a first user. You can then use that user to login and start creating projects.

Hope that helps!

Regards
Sean
